In [1]:

#Pandas Index
#Used for 3 things:
# 1) Identification 2) Selections 3) Allignment

In [2]:
import pandas as pd

In [3]:
drinks = pd.read_csv('http://bit.ly/drinksbycountry')

In [5]:
drinks.head()

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,Asia
1,Albania,89,132,54,4.9,Europe
2,Algeria,25,0,14,0.7,Africa
3,Andorra,245,138,312,12.4,Europe
4,Angola,217,57,45,5.9,Africa

In [6]:
drinks.index

Int64Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
            ...
            183, 184, 185, 186, 187, 188, 189, 190, 191, 192],
           dtype='int64', length=193)

In [8]:
drinks.columns

Index([u'country', u'beer_servings', u'spirit_servings', u'wine_servings',
       u'total_litres_of_pure_alcohol', u'continent'],
      dtype='object')

In [9]:
drinks.shape

(193, 6)

In [10]:
#Identification denotes the original index ,if filter ,it remain same

In [12]:
#After filtration 2,4,18 ... the original index states its Identifications
drinks[drinks.continent=='Africa']

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
2,Algeria,25,0,14,0.7,Africa
4,Angola,217,57,45,5.9,Africa
18,Benin,34,4,13,1.1,Africa
22,Botswana,173,35,35,5.4,Africa
26,Burkina Faso,25,7,7,4.3,Africa
27,Burundi,88,0,0,6.3,Africa
28,Cote d'Ivoire,37,1,7,4.0,Africa
29,Cabo Verde,144,56,16,4.0,Africa
31,Cameroon,147,1,4,5.8,Africa
33,Central African Republic,17,2,1,1.8,Africa
34,Chad,15,1,1,0.4,Africa
38,Comoros,1,3,1,0.1,Africa
39,Congo,76,1,9,1.7,Africa
47,DR Congo,32,3,1,2.3,Africa
49,Djibouti,15,44,3,1.1,Africa
53,Egypt,6,4,1,0.2,Africa
55,Equatorial Guinea,92,0,233,5.8,Africa
56,Eritrea,18,0,0,0.5,Africa
58,Ethiopia,20,3,0,0.7,Africa
62,Gabon,347,98,59,8.9,Africa
63,Gambia,8,0,1,2.4,Africa
66,Ghana,31,3,10,1.8,Africa
70,Guinea,9,0,2,0.2,Africa
71,Guinea-Bissau,28,31,21,2.5,Africa
88,Kenya,58,22,2,1.8,Africa
95,Lesotho,82,29,0,2.8,Africa
96,Liberia,19,152,2,3.1,Africa
97,Libya,0,0,0,0.0,Africa
100,Madagascar,26,15,4,0.8,Africa
101,Malawi,8,11,1,1.5,Africa
104,Mali,5,1,1,0.6,Africa
107,Mauritania,0,0,0,0.0,Africa
108,Mauritius,98,31,18,2.6,Africa
114,Morocco,12,6,10,0.5,Africa
115,Mozambique,47,18,5,1.3,Africa
117,Namibia,376,3,1,6.8,Africa
123,Niger,3,2,1,0.1,Africa
124,Nigeria,42,5,2,9.1,Africa
142,Rwanda,43,2,0,6.8,Africa
148,Sao Tome & Principe,56,38,140,4.2,Africa
150,Senegal,9,1,7,0.3,Africa
152,Seychelles,157,25,51,4.1,Africa
153,Sierra Leone,25,3,2,6.7,Africa
158,Somalia,0,0,0,0.0,Africa
159,South Africa,225,76,81,8.2,Africa
162,Sudan,8,13,0,1.7,Africa
164,Swaziland,90,2,2,4.7,Africa
172,Togo,36,2,19,1.3,Africa
175,Tunisia,51,3,20,1.3,Africa
179,Uganda,45,9,0,8.3,Africa
183,Tanzania,36,6,1,5.7,Africa
191,Zambia,32,19,4,2.5,Africa
192,Zimbabwe,64,18,4,4.7,Africa

In [13]:
#selection